TITLE = 'Typing Trainer'

HOME_BUTTON = 'HOME'
LEVELS_BUTTON = 'LEVELS'
STATISTICS_BUTTON = 'STATISTICS'
UPLOAD_BUTTON = 'UPLOAD'
RESTART_BUTTON = 'RESTART'
NEXT_BUTTON = 'NEXT'

LEVELS_HEADER = 'Levels'
UPLOAD_HEADER = 'Upload Level'
STATISTICS_HEADER = 'Statistics'

SPEED_TEXT = 'SPEED'
SPEED_RESOLUTION = 'WPM'
ACCURACY_TEXT = 'ACCURACY'
ACCURACY_RESOLUTION = '%'

ERROR_INVALID_FILE = 'This file is not valid!'

INSTRUCTION_PATH = 'constraints/instruction.html'
STATISTICS_PATH = 'saves/stats.pickle'
LEVEL_PATH_FIRST = 'levels/level'
LEVEL_PATH_LAST = '.txt'
